apiVersion: v1
kind: Service
metadata:
 name: wordpress
 annotations:
  metallb.universe.tf/allow-shared-ip: shared
spec:
 selector:
  app: wordpress
 type: LoadBalancer
 ports:
 - port: 5050
   name: wordpress-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
spec:
 replicas: 1
 selector:
  matchLabels:
   app: wordpress
 template:
  metadata:
   labels:
    app: wordpress
  spec:
   containers:
   - name: wordpress
     image: wordpress
     imagePullPolicy: Never
